### ISSUE TITLE
Web is not working

### ISSUE THREAD

**Issue by anwarulislam** [zubairehman/flutter_boilerplate_project#93]
#86 null-safety branch

When I run the app on the web it isn't working. In the console, I see something like this: 
```
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
```
getApplicationDocumentsDirectory is not working on flutter web.

**Comment by AndreCox** [comment]
Looks like this is the full log, might as well put it here if anyone has any ideas. In the meantime I'll try to figure something out.
```
Error: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)   
    at Object.throw_ [as throw] (http://localhost:31125/dart_sdk.js:5041:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:31125/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:31125/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:31125/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:31125/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:31125/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:31125/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:31125/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:31125/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:31125/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:31125/dart_sdk.js:37532:13)
    at http://localhost:31125/dart_sdk.js:33303:9
Error: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
    at Object.throw_ [as throw] (http://localhost:31125/dart_sdk.js:5041:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:31125/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:31125/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:31125/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:31125/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:31125/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:31125/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:31125/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:31125/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:31125/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:31125/dart_sdk.js:37532:13)
    at http://localhost:31125/dart_sdk.js:33303:9
Error: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
    at Object.throw_ [as throw] (http://localhost:31125/dart_sdk.js:5041:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:31125/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:31125/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:31125/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:31125/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:31125/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:31125/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:31125/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:31125/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:31125/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:31125/dart_sdk.js:37532:13)
    at http://localhost:31125/dart_sdk.js:33303:9
```

**Comment by zyxgo** [comment]
facing same issue when running web

**Comment by nguyenhaduchieu** [comment]
Please support flutter 2.2 with web app and responsive ios/android/web/macos all in one.

**Comment by abdullahehab** [comment]
facing same issue when running web

**Comment by zubairehman** [comment]
Apologies for the delay. The latest changes have been merged into the main branch, and the issue should now be resolved. Please pull the latest changes and let us know if you encounter any further issues.
